# Generated by Django 5.0.7 on 2024-07-23 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alarmtime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='appname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='eyemode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchmode',
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyemode', models.BooleanField()),
                ('watchmode', models.BooleanField()),
                ('alarmtime', models.TimeField(null=True)),
                ('appname', models.CharField(max_length=256)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
